using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using OS.Infrastructure.Security;
using Serilog;

namespace OS.Infrastructure.Data;

public sealed class PostgresProcessManager : IAsyncDisposable
{
    private const int DefaultPort = 5432;
    private const string HostAddress = "127.0.0.1";
    private const int StartupTimeoutSeconds = 30;
    private readonly string _binDirectory;
    private readonly string _dataDirectory;
    private readonly string _certificateDirectory;
    private readonly int _port;
    private readonly string _logPath;
    private readonly string _hbaPath;
    private readonly string _hashFilePath;
    private readonly string _postgresExePath;
    private readonly string _pgIsReadyExePath;
    private Process? _postgresProcess;
    private IntPtr _jobHandle = IntPtr.Zero;
    private bool _disposed;

    public PostgresProcessManager(
        string binDirectory,
        string dataDirectory,
        string certificateDirectory,
        int port = DefaultPort)
    {
        _binDirectory = string.IsNullOrWhiteSpace(binDirectory)
            ? throw new ArgumentException("PostgreSQL binary directory is required.", nameof(binDirectory))
            : binDirectory;
        _dataDirectory = string.IsNullOrWhiteSpace(dataDirectory)
            ? throw new ArgumentException("PostgreSQL data directory is required.", nameof(dataDirectory))
            : dataDirectory;
        _certificateDirectory = string.IsNullOrWhiteSpace(certificateDirectory)
            ? throw new ArgumentException("PostgreSQL certificate directory is required.", nameof(certificateDirectory))
            : certificateDirectory;
        _port = port;
        _logPath = Path.Combine(_dataDirectory, "postgres.log");
        _hbaPath = Path.Combine(_dataDirectory, "pg_hba.conf");
        _hashFilePath = Path.Combine(_binDirectory, "binaries.sha256");
        _postgresExePath = Path.Combine(_binDirectory, "postgres.exe");
        _pgIsReadyExePath = Path.Combine(_binDirectory, "pg_isready.exe");

        ValidatePaths();
    }

    public async Task StartAsync(CancellationToken cancellationToken = default)
    {
        EnsureDirectories();
        ValidateBinaryIntegrity();
        EnsureDataDirectory();
        WritePgHba();
        await StartPostgresProcessAsync(cancellationToken).ConfigureAwait(false);
        await WaitForServerReadyAsync(cancellationToken).ConfigureAwait(false);
    }

    private void ValidatePaths()
    {
        if (!Directory.Exists(_binDirectory))
            throw new DirectoryNotFoundException($"PostgreSQL binaries directory not found: {_binDirectory}");

        if (!Directory.Exists(_certificateDirectory))
            throw new DirectoryNotFoundException($"PostgreSQL certificate directory not found: {_certificateDirectory}");

        if (!File.Exists(_postgresExePath))
            throw new FileNotFoundException("postgres.exe not found in PostgreSQL binary directory.", _postgresExePath);

        if (!File.Exists(_pgIsReadyExePath))
            throw new FileNotFoundException("pg_isready.exe not found in PostgreSQL binary directory.", _pgIsReadyExePath);
    }

    private void EnsureDirectories()
    {
        Directory.CreateDirectory(_dataDirectory);
    }

    private void EnsureDataDirectory()
    {
        if (File.Exists(Path.Combine(_dataDirectory, "PG_VERSION")))
            return;

        var templateData = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Database", "pg_data");
        if (!Directory.Exists(templateData))
            throw new InvalidOperationException($"PostgreSQL template data directory is missing: {templateData}");

        CopyDirectory(templateData, _dataDirectory);
    }

    private void CopyDirectory(string source, string destination)
    {
        foreach (var dir in Directory.GetDirectories(source, "*", SearchOption.AllDirectories))
        {
            Directory.CreateDirectory(dir.Replace(source, destination));
        }

        foreach (var file in Directory.GetFiles(source, "*", SearchOption.AllDirectories))
        {
            var targetFile = file.Replace(source, destination);
            File.Copy(file, targetFile, overwrite: true);
        }
    }

    private void WritePgHba()
    {
        var content = new StringBuilder();
        content.AppendLine("# PostgreSQL host-based authentication configuration generated by ClinicOS");
        content.AppendLine("# For local connections, force TLS and SCRAM-SHA-256 authentication.");
        content.AppendLine("hostssl all all 127.0.0.1/32 scram-sha-256");
        content.AppendLine("hostssl all all ::1/128 scram-sha-256");
        File.WriteAllText(_hbaPath, content.ToString(), Encoding.UTF8);
    }

    private void ValidateBinaryIntegrity()
    {
        if (!File.Exists(_hashFilePath))
            return;

        var expected = File.ReadAllText(_hashFilePath).Trim();
        if (string.IsNullOrWhiteSpace(expected))
            return;

        var actual = ComputeBinariesHash(_binDirectory);
        if (!string.Equals(actual, expected, StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException("PostgreSQL binary integrity validation failed.");
    }

    private static string ComputeBinariesHash(string directory)
    {
        var files = Directory.EnumerateFiles(directory, "*", SearchOption.AllDirectories)
            .OrderBy(path => path, StringComparer.OrdinalIgnoreCase)
            .ToList();

        using var sha256 = SHA256.Create();
        foreach (var file in files)
        {
            var relativePath = Path.GetRelativePath(directory, file).Replace(Path.DirectorySeparatorChar, '/');
            var pathBytes = Encoding.UTF8.GetBytes(relativePath);
            sha256.TransformBlock(pathBytes, 0, pathBytes.Length, null, 0);

            var contentBytes = File.ReadAllBytes(file);
            sha256.TransformBlock(contentBytes, 0, contentBytes.Length, null, 0);
        }

        sha256.TransformFinalBlock(Array.Empty<byte>(), 0, 0);
        return Convert.ToHexString(sha256.Hash ?? Array.Empty<byte>());
    }

    private Task StartPostgresProcessAsync(CancellationToken cancellationToken)
    {
        if (_postgresProcess is not null)
            return Task.CompletedTask;

        var processStartInfo = new ProcessStartInfo
        {
            FileName = _postgresExePath,
            WorkingDirectory = _binDirectory,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        processStartInfo.ArgumentList.Add("-D");
        processStartInfo.ArgumentList.Add(_dataDirectory);
        processStartInfo.ArgumentList.Add("-p");
        processStartInfo.ArgumentList.Add(_port.ToString());
        processStartInfo.ArgumentList.Add("-c");
        processStartInfo.ArgumentList.Add("listen_addresses=127.0.0.1");
        processStartInfo.ArgumentList.Add("-c");
        processStartInfo.ArgumentList.Add("ssl=on");
        processStartInfo.ArgumentList.Add("-c");
        processStartInfo.ArgumentList.Add($"ssl_cert_file={Path.Combine(_certificateDirectory, "server.crt")}");
        processStartInfo.ArgumentList.Add("-c");
        processStartInfo.ArgumentList.Add($"ssl_key_file={Path.Combine(_certificateDirectory, "server.key")}");
        processStartInfo.ArgumentList.Add("-c");
        processStartInfo.ArgumentList.Add($"hba_file={_hbaPath}");
        processStartInfo.ArgumentList.Add("-c");
        processStartInfo.ArgumentList.Add("logging_collector=on");
        processStartInfo.ArgumentList.Add("-c");
        processStartInfo.ArgumentList.Add("log_destination=stderr");

        _postgresProcess = new Process { StartInfo = processStartInfo, EnableRaisingEvents = true };
        _postgresProcess.OutputDataReceived += (_, e) => { if (!string.IsNullOrEmpty(e.Data)) File.AppendAllText(_logPath, e.Data + Environment.NewLine); };
        _postgresProcess.ErrorDataReceived += (_, e) => { if (!string.IsNullOrEmpty(e.Data)) File.AppendAllText(_logPath, e.Data + Environment.NewLine); };

        if (!_postgresProcess.Start())
            throw new InvalidOperationException("Failed to start PostgreSQL server process.");

        _postgresProcess.BeginOutputReadLine();
        _postgresProcess.BeginErrorReadLine();

        _jobHandle = CreateAndConfigureJobObject();
        if (_jobHandle == IntPtr.Zero)
            throw new InvalidOperationException("Failed to create PostgreSQL job object.");

        if (!AssignProcessToJobObject(_jobHandle, _postgresProcess.Handle))
            throw new InvalidOperationException("Failed to assign PostgreSQL process to job object.");
        return Task.CompletedTask;
    }

    private static IntPtr CreateAndConfigureJobObject()
    {
        var handle = CreateJobObject(IntPtr.Zero, null);
        if (handle == IntPtr.Zero)
            throw new InvalidOperationException("Unable to create job object.");

        var info = new JOBOBJECT_EXTENDED_LIMIT_INFORMATION
        {
            BasicLimitInformation = new JOBOBJECT_BASIC_LIMIT_INFORMATION
            {
                LimitFlags = JobObjectLimitKillOnJobClose
            }
        };

        var length = (uint)Marshal.SizeOf<JOBOBJECT_EXTENDED_LIMIT_INFORMATION>();
        var extendedInfoPtr = Marshal.AllocHGlobal((int)length);
        try
        {
            Marshal.StructureToPtr(info, extendedInfoPtr, false);
            if (!SetInformationJobObject(handle, JOBOBJECTINFOCLASS.JobObjectExtendedLimitInformation, extendedInfoPtr, length))
                throw new InvalidOperationException("Unable to set job object information.");
        }
        finally
        {
            Marshal.FreeHGlobal(extendedInfoPtr);
        }

        return handle;
    }

    private async Task WaitForServerReadyAsync(CancellationToken cancellationToken)
    {
        var start = DateTime.UtcNow;
        while (DateTime.UtcNow - start < TimeSpan.FromSeconds(StartupTimeoutSeconds))
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (_postgresProcess is null || _postgresProcess.HasExited)
                throw new InvalidOperationException("PostgreSQL process exited before the server became ready.");

            var ready = await CheckPostgresAliveAsync(cancellationToken).ConfigureAwait(false);
            if (ready)
                return;

            await Task.Delay(500, cancellationToken).ConfigureAwait(false);
        }

        throw new TimeoutException("PostgreSQL did not become ready within the configured timeout.");
    }

    private async Task<bool> CheckPostgresAliveAsync(CancellationToken cancellationToken)
    {
        using var process = new Process
        {
            StartInfo = new ProcessStartInfo
            {
                FileName = _pgIsReadyExePath,
                WorkingDirectory = _binDirectory,
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false,
                CreateNoWindow = true
            }
        };

        process.StartInfo.ArgumentList.Add("-h");
        process.StartInfo.ArgumentList.Add(HostAddress);
        process.StartInfo.ArgumentList.Add("-p");
        process.StartInfo.ArgumentList.Add(_port.ToString());
        process.StartInfo.ArgumentList.Add("-q");

        process.Start();
        await process.WaitForExitAsync(cancellationToken).ConfigureAwait(false);
        return process.ExitCode == 0;
    }

    public async ValueTask DisposeAsync()
    {
        if (_disposed)
            return;

        if (_postgresProcess is not null && !_postgresProcess.HasExited)
        {
            try
            {
                _postgresProcess.Kill(entireProcessTree: true);
            }
            catch (InvalidOperationException ex)
            {
                Log.Warning(ex, "No se pudo finalizar el proceso PostgreSQL.");
            }
            finally
            {
                await _postgresProcess.WaitForExitAsync().ConfigureAwait(false);
                _postgresProcess.Dispose();
                _postgresProcess = null;
            }
        }

        if (_jobHandle != IntPtr.Zero)
        {
            CloseHandle(_jobHandle);
            _jobHandle = IntPtr.Zero;
        }

        _disposed = true;
    }

    [DllImport("kernel32.dll", SetLastError = true)]
    private static extern IntPtr CreateJobObject(IntPtr lpJobAttributes, string? lpName);

    [DllImport("kernel32.dll", SetLastError = true)]
    private static extern bool SetInformationJobObject(IntPtr hJob, JOBOBJECTINFOCLASS jobObjectInfoClass, IntPtr lpJobObjectInfo, uint cbJobObjectInfoLength);

    [DllImport("kernel32.dll", SetLastError = true)]
    private static extern bool AssignProcessToJobObject(IntPtr hJob, IntPtr hProcess);

    [DllImport("kernel32.dll", SetLastError = true)]
    private static extern bool CloseHandle(IntPtr hObject);

    private const int JobObjectLimitKillOnJobClose = 0x00002000;

    private enum JOBOBJECTINFOCLASS
    {
        JobObjectExtendedLimitInformation = 9
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct JOBOBJECT_BASIC_LIMIT_INFORMATION
    {
        public long PerProcessUserTimeLimit;
        public long PerJobUserTimeLimit;
        public int LimitFlags;
        public UIntPtr MinimumWorkingSetSize;
        public UIntPtr MaximumWorkingSetSize;
        public int ActiveProcessLimit;
        public long Affinity;
        public int PriorityClass;
        public int SchedulingClass;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct IO_COUNTERS
    {
        public ulong ReadOperationCount;
        public ulong WriteOperationCount;
        public ulong OtherOperationCount;
        public ulong ReadTransferCount;
        public ulong WriteTransferCount;
        public ulong OtherTransferCount;
    }

    [StructLayout(LayoutKind.Sequential)]
    private struct JOBOBJECT_EXTENDED_LIMIT_INFORMATION
    {
        public JOBOBJECT_BASIC_LIMIT_INFORMATION BasicLimitInformation;
        public IO_COUNTERS IoInfo;
        public UIntPtr ProcessMemoryLimit;
        public UIntPtr JobMemoryLimit;
        public UIntPtr PeakProcessMemoryUsed;
        public UIntPtr PeakJobMemoryUsed;
    }
}
